### PR TITLE
Add support for accessing values by array index

### PR DESCRIPTION
**Pull request by poly-glot**
Added indexed access to arrays or collections with brackets and without quotes.

### CODE REVIEW

**Comment by ultraq** [comment]
Hey there, thanks for the PR!  My biggest concern with it is having to lean on lodash.get for this functionality as I feel it's a bit excessive: that package is 4.4KB in size, a quarter of the entirety of thymeleafjs!
 - https://bundlephobia.com/result?p=lodash.get@4.4.2
 - https://bundlephobia.com/result?p=thymeleaf@0.20.4

However, I do like the tests and the placement of the new rule such that it works with the rest of the expression language.

If you have any ideas for implementing the functionality in a lightweight manner, then I'd be open to that.  If after a while nothing comes up, then I may merge this PR anyway and figure out something that still manages to pass those tests before a next release since I do really like those other bits 🙂

**Comment by poly-glot** [comment]
Hi @ultraq 

Thanks for your feedback. It is a fair point. I will see if I can find a suitable lightweight solution.

Regards
Junaid

**Comment by poly-glot** [comment]
Hi @ultraq 

Reported lodash dependency has been removed.

Thanks
Junaid

**Review by ultraq — APPROVED** [review]
Thanks for those changes, I'll try get a release of this out soon 👍

**Pull request merged**
